---
title: "The Structure of Datasets with tidyr"  # Title of the page
weight: 321  # Custom weight
menuTitle: "Dataset Structure" # Short title if the title is too long
tags: ["tidyr", "tidyverse", "dataset"]  # Tags to be inserted here; abbreviation of what happens on the page
---

{{% buttonShare href=\"https\:\/\/gitlab.com\/bpkleer\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}

It is important for data processing that datasets are *tidy* so that functions in R can run smoothly with the data. This means that the data must be in a specific format for the functions in R to work well with the data (less troubleshooting).

## Recap: What is a Dataset?
A dataset is always a collection of values, whether numerical or a string. These values are always organized in two ways: Each value belongs to a **variable** and an **observation**. A **variable** includes all values that have been measured for it (all observations on that variable). An **observation** includes all values that have been measured for that observation (all variable values of that *unit*).

For data to be effectively used with functions in R, they must be in a *tidy* format (also known as *long* format). A dataset is considered *tidy* when ...

- ... each variable is a column,
- ... each observation is a row,
- ... and each observational unit forms a table.
