---
title: "A Estrutura de Conjuntos de Dados com tidyr"  # Título da página
weight: 321  # Peso individual
menuTitle: "Estrutura de Dados" # Se o título for muito longo, use um título curto aqui
tags: ["tidyr", "tidyverse", "conjunto de dados"]  # Insira tags aqui; Abreviação do que acontece na página
---

{{% buttonShare href=\"https\:\/\/gitlab.com\/bpkleer\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}

É importante para o processamento de dados que os conjuntos de dados sejam *tidy*, para que as funções em R possam operar sem problemas com os dados. Isso significa que os dados devem estar em um formato específico para que as funções em R funcionem bem com os dados (menos *troubleshooting*).

## Recapitulando: O que é um conjunto de dados?
Um conjunto de dados é sempre uma coleção de valores, seja numérico ou uma string. Esses valores são sempre organizados de duas maneiras: Cada valor pertence a uma **Variável** e a uma **Observação**. Uma **Variável** inclui todos os valores que foram medidos para ela (ou seja, todas as observações nessa variável). Uma **Observação** inclui todos os valores que foram medidos para essa observação (ou seja, todos os valores das variáveis dessa *unidade*).

Para que os dados possam ser bem utilizados com as funções em R, eles devem estar em um formato *tidy* (também conhecido como formato *long*). Um conjunto de dados é considerado *tidy* quando ...

- ...cada variável é uma coluna,
- ...cada observação é uma linha,
- ...e cada unidade de observação forma uma tabela.
