---
title: "Count Plots"  # Titel der Seite
weight: 143  # Individuelles Gewicht 
menuTitle: "Count Plots" # Falls Titel zulang ist, hier Kurztitel
tags: ["count plots", "ggplot"]  # Tags hiereinsetzen; Kurzwort, was auf der Seite passsiert
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = TRUE,   # Code wird angezeigt
  eval = FALSE,  # Code wird nicht ausgeführt
  message = FALSE, # Messages werden nicht angezeigt
  warnings = FALSE # warnings werden nicht angezeigt
)

library("tidyverse")
library("beyonce")

pss <- readRDS("./data/pss.rds")
```

Eine andere gute Möglichkeit, um zwei pseudometrische Variablen darzustellen, ist der **count plot**. Hier werden die Kombinationen, die häufiger vorkommen größer dargestellt. Dazu rufen wir die Funktion `geom_count()` auf:

```{r count, eval=TRUE}
countplot <- ggplot( 
  pss, 
  aes(
    trstplt, 
    trstlgl
  )
) + 
  geom_count()

countplot
```

## Coloring
Auch hier können wir Farben hinzufügen:
```{r count2, eval=TRUE}
ggplot(
  pss, 
  aes(
    trstplt, 
    trstlgl)) + 
  geom_count(
    aes(
      color = ..n.., 
      size = ..n..
    )
  ) +  
  guides(color = "legend")  
```

Zuguterletzt lernst du noch kennen, wie du eine bivariate Verteilung auch darstellen kannst!