---
title: "Multivariate lin. Regression mit polytomen kategoriellen Variablen"  # Titel der Seite
weight: 105  # Individuelles Gewicht 
menuTitle: "Polytome kategorielle Variablen" # Falls Titel zulang ist, hier Kurztitel
tags: ["regression", "kategoriell", "polytom"]  # Tags hiereinsetzen; Kurzwort, was auf der Seite passsiert
---



<p>Wir können nicht nur dichotome, sondern auch polytome kategorielle Variablen in das Regressionsmodell hinzufügen. Wir möchten nun die Variable <code>edu</code> ins Modell aufnehmen. Diese Variable beinhaltet den höchsten Bildungsabschluss der befraten Person. Welche theoretischen Annahmen könnten wir für den Effekt von <code>edu</code> treffen?</p>
<div id="berechnen-des-modells" class="section level2">
<h2>Berechnen des Modells</h2>
<p>Wir fügen einfach die Variable, wie zuvor, in der <code>lm()</code>-Funktion hinzu:</p>
<pre class="r"><code>olsModel4 &lt;- lm(
    stfdem ~ 1 + stfeco + trstlgl + gndr + edu,   
    data = pss
)
summary(olsModel4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = stfdem ~ 1 + stfeco + trstlgl + gndr + edu, data = pss)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.7867 -1.1246  0.0123  1.1391  5.8527 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      0.535964   0.112218   4.776 1.84e-06 ***
## stfeco           0.854641   0.014166  60.332  &lt; 2e-16 ***
## trstlgl         -0.044393   0.013572  -3.271  0.00108 ** 
## gndrmale         0.001836   0.051229   0.036  0.97142    
## eduES-ISCED II   0.168395   0.076925   2.189  0.02864 *  
## eduES-ISCED III  0.343037   0.076832   4.465 8.21e-06 ***
## eduES-ISCED IV   0.419061   0.085739   4.888 1.06e-06 ***
## eduES-ISCED V    0.870502   0.125865   6.916 5.29e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.716 on 4542 degrees of freedom
##   (450 observations deleted due to missingness)
## Multiple R-squared:  0.4643, Adjusted R-squared:  0.4635 
## F-statistic: 562.3 on 7 and 4542 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>{{% tabs %}}
{{% tab name="Frage" %}}
Wie hat die Funktion <code>lm()</code> die polytome Variable in das Modell eingefügt?</p>
<p>Was ist die Referenzkategorie?</p>
<p>Und wie würde die Gleichung der Regression aussehen?
{{% /tab %}}
{{% tab name="Auflösung" %}}
Es wird der zusätzliche Effekt von den vier höchsten Ausprägungen (<code>ES-ISCED II</code>, <code>ES-ISCED III</code>, <code>ES-ISCED IV</code> und <code>ES-ISCED V</code>) gegenüber der niedrigsten Ausprägung (<code>ES-ISCED I</code>) berechnet.</p>
<p>Die Referenzkategorie ist daher <code>ES-ISCED I</code> (ausgelassene Ausprägung).</p>
<p><span class="math display">\[\begin{align*}stfdem = &amp;\beta_0 + \beta_1*stfeco + \beta_2*trstlgl + \beta_3*gndr + \\ &amp;\beta_4*eduLevelII + \beta_5*eduLevelIII + \\ &amp;\beta_6*eduLevelIV + \beta_7*eduLevelV + \\&amp;e \end{align*}\]</span>
{{% /tab %}}
{{% /tabs %}}</p>
</div>
<div id="ändern-der-referenzkategorie" class="section level2">
<h2>Ändern der Referenzkategorie</h2>
<p>In diesem Beispiel wurde automatisch die niedrigste (bzw. erste) Ausprägung als Referenzkategorie gewählt. Doch was, wenn du z.B. die mittlere Kategorie (<code>ES-ISCED III</code>) als Referenz haben möchtest? Dies kannst du einfach mit der Funktion <code>relevel()</code> ändern. Dazu gibst du im ersten Argument die Datenquelle an (Variable <code>pss$edu</code>) und im zweiten Argument <code>ref</code> die entsprechende Ausprägung (also <code>"ES-ISCED III"</code>). <strong>Wichtig:</strong> Du musst das natürlich mit den Anweisungpfeil in der Variable im Datensatz speichern!</p>
<pre class="r"><code>pss$edu &lt;- relevel(
  pss$edu, 
  ref = &quot;ES-ISCED III&quot;
) </code></pre>
<p>Dann musst du nur das Modell erneut berechnen:</p>
<pre class="r"><code>olsModel5 &lt;- lm(
  stfdem ~ 1 + stfeco + trstlgl + gndr + edu,
  data = pss
)

summary(olsModel5)</code></pre>
<pre><code>## 
## Call:
## lm(formula = stfdem ~ 1 + stfeco + trstlgl + gndr + edu, data = pss)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.7867 -1.1246  0.0123  1.1391  5.8527 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     0.879001   0.106299   8.269  &lt; 2e-16 ***
## stfeco          0.854641   0.014166  60.332  &lt; 2e-16 ***
## trstlgl        -0.044393   0.013572  -3.271  0.00108 ** 
## gndrmale        0.001836   0.051229   0.036  0.97142    
## eduES-ISCED I  -0.343037   0.076832  -4.465 8.21e-06 ***
## eduES-ISCED II -0.174643   0.066577  -2.623  0.00874 ** 
## eduES-ISCED IV  0.076024   0.075825   1.003  0.31610    
## eduES-ISCED V   0.527465   0.119052   4.431 9.62e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.716 on 4542 degrees of freedom
##   (450 observations deleted due to missingness)
## Multiple R-squared:  0.4643, Adjusted R-squared:  0.4635 
## F-statistic: 562.3 on 7 and 4542 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>{{% tabs %}}
{{% tab name="Interpretation" %}}
Interpretiere das respezifizierte Modell. Schreibe ein paar Sätze in das Skript.</p>
<p>{{% /tab %}}
{{% tab name="Musterlösung" %}}</p>
<p>Das Modell erklärt <span class="math inline">\(46.35 %\)</span> der Varianz in <code>stfdem</code>. Der Effekt von <code>stfeco</code> ist positiv und signifikant (<span class="math inline">\(p&lt;0.001\)</span>). Personen mit höherem Vertrauen in das Rechtssystem haben eine geringe Zufriedenheit (<span class="math inline">\(\beta_2 = -0.044393\)</span>, <span class="math inline">\(p&lt;0.01\)</span>). Männliche und weibliche Befragte haben keine unterschiedliche Zufriedenheit (<span class="math inline">\(\beta_3 = 0.001836\)</span>. <span class="math inline">\(p&gt;0.05\)</span>). Im Vergleich zu Personen mit mittlerem Bildungsabschluss, haben Personen mit sehr niedrigem Abschluss (<code>ES-ISCED I</code>) und niedrigem Bildungsabschluss (<code>ES-ISCED II</code>) ein geringeres Vertrauen (<span class="math inline">\(\beta_4 = -0.343037\)</span> bzw. <span class="math inline">\(\beta_5 = -0.174643\)</span>). Beide Effekte sind signifikant. Personen mit dem höchsten Bildungsabschluss haben ein deutlich höheres Vertrauen als Personen mit mittlerem Bildungsabschluss (<span class="math inline">\(\beta_7 = 0.527465\)</span>, <span class="math inline">\(p&lt;0.001\)</span>). Personen mit dem zweithöchsten Abschluss haben ein geringfügig höheres Vertrauen (<span class="math inline">\(\beta_6 = 0.076024\)</span>), dieser Effekt ist aber nicht signifikant.
{{% /tab %}}
{{% /tabs %}}</p>
<p>So du kannst jetzt also auch schon polytome kategorielle Variablen hinzufügen und das Regressionsmodell in der Ausgabe in R interpretieren!</p>
</div>
