---
title: "Multivariate lineare Regression"  # Titel der Seite
weight: 103  # Individuelles Gewicht 
menuTitle: "Multivariates Beispiel" # Falls Titel zulang ist, hier Kurztitel
tags: ["regression", "multivariat"]  # Tags hiereinsetzen; Kurzwort, was auf der Seite passsiert
---



<p>In der Regel berechnen wir keine bivariaten Modell in den Sozialwissenschaften, da Ursache-Wirkungs-Relationen in sozialen Phänomenen nie bivariat sind. Das vorherige Modell diente lediglich zum leichteten Zugang.</p>
<p>Nun erweitern wir das Modell und berechnen eine <strong>multivariate lineare Regression</strong>. Wir möchten die Variable <code>trstlgl</code> in das Modell einfügen. Welche Effekt erwartet wir theoretisch von der Variable <code>trstlgl</code>?</p>
<pre class="r"><code>cor(
  pss$trstlgl, 
  pss$stfdem,
  method = &quot;pearson&quot;, 
  use = &quot;complete.obs&quot;
)</code></pre>
<p>Wie interpretieren wir das Ergebnis?</p>
<p><span class="math inline">\(\Rightarrow\)</span> Der Korrelationswert zwischen <code>trstlgl</code> und <code>stfdem</code> zeigt uns an, dass eine negative Korrelation vorliegt, die aber nahe <span class="math inline">\(0\)</span> liegt, so dass man davon ausgehen kann, dass kein Zusammenhang zwischen den zwei Variablen vorliegt.</p>
<div id="erweitern-des-modells" class="section level3">
<h3>Erweitern des Modells</h3>
<p>Wir erweitern das Modell um die Variable <code>trstlgl</code>.</p>
<p>{{% expand "Wie sieht unsere lineare Gleichung aus?" %}}</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1*X_1 + \beta_2*X_2 + e\]</span></p>
<p><span class="math display">\[stfdem = \beta_0 + \beta_1*stfeco + \beta_2*trstlgl + e\]</span>
{{% /expand %}}</p>
<p>Dies setzen wir einfach in der <code>lm()</code>-Funktion um:</p>
<pre class="r"><code>olsModel2 &lt;- lm(
  stfdem ~ 1 + stfeco + trstlgl,   
  data = pss
)            

summary(olsModel2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = stfdem ~ 1 + stfeco + trstlgl, data = pss)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.7076 -1.0868  0.0396  1.1660  5.8289 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.67658    0.09318   7.261 4.44e-13 ***
## stfeco       0.87361    0.01355  64.468  &lt; 2e-16 ***
## trstlgl     -0.04212    0.01319  -3.194  0.00141 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.732 on 4890 degrees of freedom
##   (107 observations deleted due to missingness)
## Multiple R-squared:  0.4598, Adjusted R-squared:  0.4596 
## F-statistic:  2081 on 2 and 4890 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>{{% tabs %}}
{{% tab name="Aufgabe" %}}
Wie interpretieren wir das Ergebnis? Schreibe ein paar Zeilen in dein Skript!</p>
<p>{{% /tab %}}
{{% tab name="Auflösung" %}}
Das Modell kann <span class="math inline">\(45.96 %\)</span> der Varianz in <code>stfdem</code> erklären. Mit jedem Anstieg in <code>stfeco</code> (Zufriedenheit mit der ökonomischen Leistung) steigt <code>stfdem</code> um <span class="math inline">\(0.87361\)</span> Punkte. Mit jedem Anstieg im Vertrauen zum Rechtssystem (<code>trstlgl</code>) sinkt die Zufriedenheit mit der Demokratie um <span class="math inline">\(-0.04212\)</span>. Beide Effekte sind signifikant (<span class="math inline">\(p&lt;0.05\)</span>).
{{% /tab %}}
{{% /tabs %}}</p>
<p>Du kannst also jetzt auch schon multivariate Modelle berechnen und weißt wie du diese interpretieren kannst!</p>
</div>
