---
title: "Multivariate lin. Regression mit dichotomen kategoriellen Variablen"  # Titel der Seite
weight: 104  # Individuelles Gewicht 
menuTitle: "Dichotome kategorielle Variablen" # Falls Titel zulang ist, hier Kurztitel
tags: ["regression", "kategoriell", "dichotom"]  # Tags hiereinsetzen; Kurzwort, was auf der Seite passsiert
---



<p>{{% buttonGit href="https://gitlab.ub.uni-giessen.de/methoden-politik/einstieg-in-r/issues/new?issue[title]=" icon="fas fa-bug" %}} {{% /buttonGit %}}</p>
<p>{{% buttonGit href="mailto:?subject=Schau%20dir%20das%20mal%20an%3A%20" icon="fas fa-paper-plane" %}} {{% /buttonGit %}}</p>
<p>{{% buttonGit href="https://t.me/share/url?url=" icon="fab fa-telegram" %}} {{% /buttonGit %}}</p>
<p>{{% buttonGit href="https://api.whatsapp.com/send?text=" icon="fab fa-whatsapp" %}} {{% /buttonGit %}}</p>
<p>{{% buttonGit href="https://twitter.com/share?url=" icon="fab fa-twitter" %}} {{% /buttonGit %}}</p>
<p>{{% buttonGit href="https://www.facebook.com/sharer/sharer.php?u=" icon="fab fa-facebook" %}} {{% /buttonGit %}}</p>
<p>In den Sozialwissenschaften nutzen wir oftmals Variablen mit nominalem oder ordinalem Skalenniveau. Diese können wir auch in das <strong>lineare Regressionsmodell</strong> als unabhängige Variable hinzufügen. Wir müssen nur verstehen, welchen zusätzlichen Effekt wir berechnen. Wir müssen <em>Dummy</em>-Variablen kreieren, die den Unterschied einer Ausprägung auf der Variablen in Referenz zu einer anderen Ausprägung angeben (Referenzkategorie). In der Funktion <code>lm()</code> ist dies leicht umzusetzen.</p>
<p>Wir möchten die Variable <code>gndr</code> mit in unser Modell aufnehmen (<em>female</em>/<em>male</em>). Welche theoretische Annahme können wir über den Effekt treffen?</p>
<p>{{% expand "Was gleichen wir in der Regressionsgleichung an?" %}}</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1*X_1 + \beta_2*X_2 + \beta_3*X_3+ e\]</span></p>
<p><span class="math display">\[stfdem = \beta_0 + \beta_1*stfeco + \beta_2*trstlgl + \beta_3*gndr + e\]</span>
{{% /expand %}}</p>
<p>Wie wir bereits wissen, hat eine dichotome Variable keine lineare Beziehung zu einer metrischen Variable. Deshalb benötigen wir <strong>Dummy-Variablen</strong>. Wir berechnen ein Modell, in dem der zusätzliche Effekt einer Ausprägung gegenüber der anderen Ausprägung geschätzt wird. Dieser Effekt ist ein
konstanter Effekt!.</p>
<p>Die Variable <code>gndr</code> hat folgende Ausprägungen:</p>
<ul>
<li><p><em>female</em></p></li>
<li><p><em>male</em></p></li>
</ul>
<div id="berechnen-des-modells" class="section level2">
<h2>Berechnen des Modells</h2>
<p>Auch hier müssen wir entsprechend der erweiterten Gleichung nur die Variable <code>gndr</code> hinzufügen:</p>
<pre class="r"><code>olsModel3 &lt;- lm(
  stfdem ~ 1 + stfeco + trstlgl + gndr,   
  data = pss
)            

summary(olsModel3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = stfdem ~ 1 + stfeco + trstlgl + gndr, data = pss)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.7490 -1.0846  0.0411  1.1642  5.7898 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.70975    0.09539   7.440 1.18e-13 ***
## stfeco       0.87435    0.01356  64.496  &lt; 2e-16 ***
## trstlgl     -0.04137    0.01319  -3.136  0.00173 ** 
## gndrmale    -0.08020    0.04957  -1.618  0.10573    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.732 on 4889 degrees of freedom
##   (107 observations deleted due to missingness)
## Multiple R-squared:  0.4601,	Adjusted R-squared:  0.4598 
## F-statistic:  1389 on 3 and 4889 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>{{% tabs %}}
{{% tab name="Frage" %}}
Was ist die Referenzkategorie?</p>
<p>Welchen Effekt berechnen wir mit der Variable <code>gndrmale</code>?</p>
<p>{{% /tab %}}
{{% tab name="Auflösung" %}}
Die Referenzkategorie ist <em>female</em>, also weibliche Befragte.</p>
<p>Der zusätzliche Effekt ist für Personen berechnet, die männlich sind (gegenüber weiblichen Personen). Männliche Personen haben also eine um <span class="math inline">\(-0.08020\)</span> niedrige Zufriedenheit als weibliche Personen.
{{% /tab %}}
{{% tab name="Interpretation des Modells" %}}
Wie interpretieren wir das Modell?</p>
<p>Schreibe ein paar Zeilen in das Skript!
{{% /tab %}}
{{% tab name="Musterlösung" %}}</p>
<p>Das Modell erklärt <span class="math inline">\(45.98 %\)</span> der Varianz in der Variable <code>stfdem</code>. Die Zufriedenheit mit der ökonomischen Leistung (<code>stfeco</code>) sowie das Vertrauen in das Rechtssystem (<code>trstlgl</code>) haben einen signifikanten Effekt auf die Zufriedenheit mit der Demokratie (<code>stfdem</code>). Der Effekt von <code>stfeco</code> ist positiv (<span class="math inline">\(\beta_1 = 0.87435\)</span>), der Effekt von Vertrauen in das Rechtssystem (<span class="math inline">\(\beta_2 = -0.04137\)</span>) und der Effekt für männliche Personen (<span class="math inline">\(\beta_3 = -0.08020\)</span>) sind beide negativ. Personen, die ein höheres Vertrauen haben oder männlich sind, haben also einge leicht geringere Zufriedenheit.
{{% /tab %}}
{{% /tabs %}}</p>
<p>{{% expand "Wenn du jetzt nochmal die Formel oben vergleichst mit der Aufgabe, sollte dir etwas auffallen! Was muss an der Formel geändert werden, damit diese tatsächlich auf das Regressionmodell passt?" %}}
In der Gleichung oben ist die Variable Geschlecht (<code>gndr</code>) aufgeführt. Tatsächlich aber fügen wir eine Variable <code>gndrmale</code> hinzu, die eben in der Ausprägung <code>1</code> angibt, dass die Person männlich ist und in der Ausprägung <code>0</code>, dass die Person nicht männlich (also in diesem dichotomen Beispiel <em>female</em>) ist.</p>
<p>Die Formel wäre daher wie folgt korrekt:
<span class="math display">\[stfdem = \beta_0 + \beta_1*stfeco + \beta_2*trstlgl + \beta_3*male + e\]</span>
{{% /expand %}}</p>
<p>Warum das relevant ist, siehst du auf der nächsten Seite! Jetzt hast du gelernt, wie du dichotome kategorielle Variablen in das Regressionsmodell aufnimmst, doch wie funktioniert es mit polytomen kategoriellen Variablen?</p>
</div>
