---
title: "Splitting a Dataset"  # Page title
weight: 313  # Custom weight 
menuTitle: "" # Short title if the title is too long
tags: ["dplyr", "tidyverse", "dataset"]  # Tags: brief description of what happens on the page
---
```{r setup, include = FALSE}
library("knitr")
library("htmltools")
library("tidyverse")
knitr::opts_chunk$set(
  echo = TRUE,   # Code wird angezeigt
  eval = FALSE,  # Code wird nicht ausgeführt
  message = FALSE, # Messages werden nicht angezeigt
  warnings = FALSE # warnings werden nicht angezeigt
)
pss <- readRDS("./data/pss.rds")

```

{{% buttonShare href=\"https\:\/\/gitlab.com\/bpkleer\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}

First, let's review how to split a dataset: We filter the cases that are relevant for our later analysis. For example, we only want to study male respondents from District 5.

{{% expand \"Which functions do we need to apply?\" %}}
Exactly, we use filter(). 

```R
pssD5M <- pss %>%
  filter(district == "Distrikt 5" & gndr == "male")

head(pssD5M)
```
{{% /expand %}}

{{% tabs groupId=\"tab1\" %}}
{{% tab name=\"Task\" %}}
Now filter the dataset for individuals living in District 1 or 12 and working more than 30 hours! Save the subset in a new object!
{{% /tab %}}
{{% tab name=\"Code\" %}}
```R
pssD1D12o30 <- pss %>%
  filter((district == "Distrikt 1" | district == "Distrikt 12") & wkhtot > 30)

head(pssD1D12o30)
```
{{% /tab %}}
{{% /tabs %}}

Sometimes you may need to merge datasets that were collected separately. You can learn that on the next page. However, feel free to skip the next page if you don't find it relevant for you! 

{ /* examples */ }
