---
title: "Dividindo um Conjunto de Dados"  # Título da página
weight: 313  # Peso individual
menuTitle: "" # Se o título for muito longo, coloque um título curto aqui
tags: ["dplyr", "tidyverse", "conjunto de dados"]  # Insira as tags aqui; Palavra curta que descreve o que acontece na página
---
```{r setup, include = FALSE}
library("knitr")
library("htmltools")
library("tidyverse")
knitr::opts_chunk$set(
  echo = TRUE,   # Code wird angezeigt
  eval = FALSE,  # Code wird nicht ausgeführt
  message = FALSE, # Messages werden nicht angezeigt
  warnings = FALSE # warnings werden nicht angezeigt
)
pss <- readRDS("./data/pss.rds")

```

{{% buttonShare href=\"https\:\/\/gitlab.com\/bpkleer\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}

Primeiro, vamos revisar como dividir um conjunto de dados: filtramos os casos relevantes para nossa análise posterior. Por exemplo, queremos pesquisar apenas entrevistados do sexo masculino do Distrito 5.

{{% expand \"Quais funções devemos usar?\" %}}
Precisamente, usamos a função filter().

```R
pssD5M <- pss %>%
  filter(district == "Distrikt 5" & gndr == "male")

head(pssD5M)
```
{{% /expand %}}

{{% tabs groupId=\"tab1\" %}}
{{% tab name=\"Tarefa\" %}}
Agora filtre o conjunto de dados para pessoas que vivem no Distrito 1 ou 12 e trabalham mais de 30 horas! Salve o subconjunto em um novo objeto!
{{% /tab %}}
{{% tab name=\"Código\" %}}
```R
pssD1D12o30 <- pss %>%
  filter((district == "Distrikt 1" | district == "Distrikt 12") & wkhtot > 30)

head(pssD1D12o30)
```
{{% /tab %}}
{{% /tabs %}}

Às vezes, é necessário unir conjuntos de dados que foram coletados separadamente. Você pode aprender isso na próxima página. No entanto, você também pode pular a próxima página se achar que não é relevante para você!
