---
title: "Teilen eines Datensatzes"  # Titel der Seite
weight: 313  # Individuelles Gewicht 
menuTitle: "" # Falls Titel zulang ist, hier Kurztitel
tags: ["dplyr", "tidyverse", "datensatz"]  # Tags hiereinsetzen; Kurzwort, was auf der Seite passsiert
---
```{r setup, include = FALSE}
library("knitr")
library("htmltools")
library("tidyverse")
knitr::opts_chunk$set(
  echo = TRUE,   # Code wird angezeigt
  eval = FALSE,  # Code wird nicht ausgeführt
  message = FALSE, # Messages werden nicht angezeigt
  warnings = FALSE # warnings werden nicht angezeigt
)
pss <- readRDS("./data/pss.rds")

```

{{% buttonShare href=\"https\:\/\/gitlab.com\/bpkleer\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:?subject=Schau\%20dir\%20das\%20mal\%20an\%3A\%20\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}

Zuerst wiederholen wir noch einmal, wie wir einen Datensatz teilen: Wir filtern die Fälle, die für unsere spätere Analyse relevant sind. Zum Beispiel wollen wir nur männliche Befragte aus Distrikt 5 forschen.

{{% expand \"Welche Funktionen müssen wir anwenden?\" %}}
Genau wir nutzen filter(). 

```R
pssD5M <- pss %>%
  filter(district == "Distrikt 5" & gndr == "male")

head(pssD5M)
```
{{% /expand %}}

{{% tabs groupId=\"tab1\" %}}
{{% tab name=\"Aufgabe\" %}}
Filtere jetzt einmal den Datensatz nach Personen, die in Distrikt 1 oder 12 leben und mehr als 30h arbeiten! Speichere das Subset in einem neuen Objekt!
{{% /tab %}}
{{% tab name=\"Code\" %}}
```R
pssD1D12o30 <- pss %>%
  filter((district == "Distrikt 1" | district == "Distrikt 12") & wkhtot > 30)

head(pssD1D12o30)
```
{{% /tab %}}
{{% /tabs %}}

Manchmal muss man selbst auch Datensätze, die getrennt erhoben wurden, selbst zusammenfügen. Das kannst du auf der nächsten Seite lernen. Die nächste Seite kannst du aber auch überspringen, wenn du findest, dass das für dich nicht relevant ist!