---
title: "Da Coleta de Dados ao Conjunto de Dados"  # Título da página
weight: 111  # Peso individual
menuTitle: "Coleta de Dados" # Se o título for muito longo, use um título curto aqui
tags: ["coleta-de-dados", "conjunto-de-dados"]  # Insira tags aqui; Abreviação do que acontece na página
---

{{% buttonShare href=\"https\:\/\/gitlab.com\/bpkleer\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}

No R, você geralmente trabalha com dados já coletados. No entanto, para entender melhor o objeto **data frame**, nesta página você poderá seguir os passos da coleta de dados ao conjunto de dados. Isso ajudará você a compreender melhor o objeto **data frame** no R.

Mais adiante, usaremos um conjunto de dados de treinamento fictício chamado *Panem Social Survey*, inspirado no [European Social Survey](https://europeansocialsurvey.com). A vantagem é que você poderá praticar primeiro com um conjunto de dados de treinamento muito menor antes de trabalharmos com conjuntos de dados reais (maiores) presencialmente. 
Você já encontrará o conjunto de dados e o codebook do **PSS** no projeto do RStudio. Se desejar salvá-lo manualmente em seu computador, você pode encontrá-lo aqui:

{{%attachments style=\"grey\" title=\"Conjuntos de Dados\" /%}}

Também nos anexos, você encontrará um PDF com o nome `from-survey-to-data.pdf`. Faça o download e dê uma olhada!

No arquivo há um trecho de quatro perguntas (variáveis do conjunto de dados) que foram coletadas neste conjunto de dados fictício. **Dica:** No Codebook, você obterá informações mais detalhadas sobre o tipo de medição de cada variável.

{{% expand \"Agora, pense rapidamente em qual nível de escala as perguntas individuais (variáveis) estão e com que tipo de vetor (numérico, inteiro, caractere, booleano) você as implementaria no R.\" %}}

A pergunta de ID está em um nível de escala nominal, apenas diferenças entre as manifestações podem ser identificadas. É melhor implementar isso com um vetor *character*.

O gênero é medido em um nível de escala nominal. Portanto, recomenda-se um vetor *character* ou, especificamente, um *factor*.

A idade está claramente em um nível de escala métrica e, como medimos a idade em anos completos, um vetor *integer* é suficiente. No entanto, um vetor *numeric* também seria correto.

A renda familiar é questionada de forma ordinal. Existem diferenças entre as manifestações e uma clara ordem, mas as distâncias não são iguais! No R, isso pode ser implementado como um *ordered factor*.

Por fim, a satisfação com a democracia em Panem é questionada. Isso está claramente em um nível de escala ordinal, pois há mais de dez manifestações, também pode ser interpretado como um nível de escala pseudométrico. No R, isso seria implementado com um vetor *numeric* ou *integer*.

{{% /expand %}}

Como você já deve ter entendido, um conjunto de dados não é nada mais do que uma coleção de várias variáveis de pessoas entrevistadas que são processadas em conjunto. Portanto, conjuntos de dados são processados ou lidos em forma de tabelas. Essas tabelas de dados têm duas dimensões: **Linhas** e **Colunas**.

Você aprenderá sobre a estrutura de uma tabela de dados na próxima página.
