---
title: "From Data Collection to Dataset"  # Page title
weight: 111  # Custom weight
menuTitle: "Data Collection" # Short title if necessary
tags: ["data collection", "dataset"]  # Tags describing the content of the page
---

{{% buttonShare href=\"https\:\/\/gitlab.com\/bpkleer\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}

In R, you usually work with already collected data. However, to better understand the **data frame** object, on this page, you will be able to follow the steps from data collection to dataset. This will help you in understanding the **data frame** object in R.

Later on, we will be using a fictional training dataset called *Panem Social Survey*, inspired by the [European Social Survey](https://europeansocialsurvey.com). The advantage is that you can practice with a much smaller training dataset first before working with real (larger) datasets in person. 
You can already find the dataset and the codebook for **PSS** in the RStudio project. If you want to manually save it on your computer again, you can find it here:

{{%attachments style=\"grey\" title=\"Data sets\" /%}}

You will also find a PDF named `from-survey-to-data.pdf` in the attachments. Download it and take a look! 

In the file is an excerpt of four questions (variables from the dataset) that were collected in this fictional dataset. **Tip:** In the codebook, you will get more detailed information about the type of measurement of each variable.

{{% expand \"Now take a moment to consider the scale level of each question (variable) and with what type of vector (numeric, integer, character, boolean) you would implement them in R.\" %}}

The ID question is at a nominal scale level, only differences between the manifestations can be identified. It is best to implement this with a *character* vector.

Gender is measured at a nominal scale level. Therefore, a *character* vector or specifically a *factor* is recommended.

Age is clearly at a metric scale level, and since we measure age in whole years, an *integer* vector is sufficient. However, a *numeric* vector would also be correct.

Household income is queried ordinally. There are differences between the manifestations and a clear ranking, but the intervals are not equal! In R, this can be implemented as an *ordered factor*.

Lastly, the satisfaction with democracy in Panem is queried. This is clearly at an ordinal scale level, and since there are more than ten manifestations, it can also be interpreted as a pseudo-metric scale level. In R, this would then be implemented with a *numeric* or *integer* vector.
{{% /expand %}}

As you have probably already understood, a dataset is nothing more than a collection of several variables from surveyed individuals that are processed together. Therefore, datasets are processed or read in tabular form. These data tables have two dimensions: **Rows** and **Columns**.

You will learn about the structure of a data table on the next page.
