---
title: "Regressionsdiagnostik"  # Titel der Seite
weight: 301  # Individuelles Gewicht 
menuTitle: "Regressionsdiagnostik" # Falls Titel zulang ist, hier Kurztitel
tags: ["regressionsdiagnostik"]  # Tags hiereinsetzen; Kurzwort, was auf der Seite passsiert
---

{{% buttonShare href=\"https\:\/\/gitlab.ub.uni-giessen.de\/methoden-politik\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:?subject=Schau\%20dir\%20das\%20mal\%20an\%3A\%20\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}

In diesem Kapitel werden die Annahmen der **linearen Regression** getestet. Ausgangspunkt ist dabei das Modell `olsModel2` aus dem vorherigen Teil.

$stfdem_i = \beta_0 + \beta_1*stfeco_i + \beta_2*trstlgl_i + e_i$ (olsModel2)

Lade das Regressionsmodell in das **Environment** oder berechne das oben genannte Modell neu.

Für `olsModel2` erhalten wir folgende Regressionsgleichung:

$$ stfdem_i = 0.67658 + 0.87361 * stfeco_i - 0.04212 * trstlgl_i + e_i $$

Die Bestandteile der Vorhersage sind:

$$ \widehat{stfdem_i} = 0.67658 + 0.87361 * stfeco_i - 0.04212 * trstlgl_i $$

{{% tabs %}}
{{% tab name=\"Frage\" %}}
1. Was ist der Effekt von `stfeco`? 

2. Welchen Wert sagt das Modell für eine Person voraus, die die Zufriedenheit mit der ökonomischen Leistung mit $10$ und ein Vertrauen in das Rechtssystem mit $5$ angibt?

{{% /tab %}}
{{% tab name=\"Auflösung\" %}}
1. Der Effekt von `stfeco` beträgt $0.87361$.

2. $\hat{stfdem} = 0.67658 + 0.87361 * 10 - 0.04212 * 5 = 9.20208$
{{% /tab %}}
{{% /tabs %}}

## Annahmen der linearen Regression

Als Sozialwissenschaftler:innen berechnen wir Modelle, die wir hinsichtlich der mathematischen Annahmen prüfen müssen. Es gibt eine Reihe an Funktionen mit denen wir die **Regressionsdiagnostik** berechnen können. Da wir in den Sozialwissenschaften selten perfekte Datensätze haben (Non-Response, `NA's`), sind diese Funktionen oftmals zu restriktiv. In der Anwendung entscheiden wir oft über Annäherung an die Annahmen, und nicht ob die Annahmen voll erfüllt sind. Wir prüfen oft, ob mögliche Verletzungen *gering* genug sind, so dass die Annahme gilt.


**Dies sind die Annahmen der linearen Regression:**
{{% tabs %}}
{{% tab name=\"Annahmen\" %}}
1. lineare Beziehung

2. $\epsilon_i \sim \mathcal{N}(0, \sigma^2)$

3. $Var(\epsilon_i) = \sigma^2$ (**Homoskedastizität**)

4. $Cov(\epsilon_i, \epsilon_j) = 0, i \neq j$ (**Auto-Korrelation**)

5. keine lineare Abhängigkeit unter den unabhängigen Variablen (**Multikollinearität**)

6. keine einflussreichen Fälle
{{% /tab %}}
{{% tab name=\"Wirkung bei Verletzung\" %}}
1. verzerrte Schätzer

2. invalide Signifikanztest, verzerrte Schätzer

3. verzerrte Schätzer

4. ineffiziente Schätzung 

5. verzerrte Schätzer

6. verzerrte Schätzer
{{% /tab %}}
{{% tab name=\"Mögliche Lösung\" %}}
1. nicht-lineare Transformation

2. *nichts!*

3. Transformation der abhängigen Variable (oder der linearen Gleichung)

4. nicht-lineare Transformation

5. Variablen entfernen

6. Beobachtungen entfernen (muss aber theoretisch begründbar sein!)
{{% /tab %}}
{{% tab name=\"Testvorgehen\" %}}
1. Plot Inspektion

2. Plot Inspektion (Shapiro-Wilk-Test)

3. Breusch-Pagan-Test

4. Durbin-Watson-Statistik

5. Korrelation zwischen unabhängigen Variablen sowie VIF / Tolerance factor

6. Cook's D
{{% /tab %}}
{{% /tabs %}}

Auf den nächsten Seiten wirst du Schritt für Schritt die Annahmen testen. 
