---
title: "Diagnóstico de Regressão"  # Título da página
weight: 301  # Peso individual
menuTitle: "Diagnóstico de Regressão" # Título curto, caso o título seja longo
tags: ["diagnóstico de regressão"]  # Tags aqui; Palavra-chave do que acontece na página
---

{{% buttonShare href=\"https\:\/\/gitlab.com\/bpkleer\/einstieg-in-statistik\/issues\/new?issue[title]=\" icon=\"fas fa-bug\" %}} {{% /buttonShare %}} 

{{% buttonShare href=\"mailto\:\" icon=\"fas fa-paper-plane\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/t.me\/share\/url?url=\" icon=\"fab fa-telegram\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/api.whatsapp.com\/send?text=\" icon=\"fab fa-whatsapp\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/twitter.com\/share?url=\" icon=\"fab fa-x-twitter\" %}} {{% /buttonShare %}}

{{% buttonShare href=\"https\:\/\/www.facebook.com\/sharer\/sharer.php?u=\" icon=\"fab fa-facebook\" %}} {{% /buttonShare %}}

{{% button href=\"https\:\/\/bmc.link\/bpkleerw\" icon=\"fa-solid fa-beer-mug-empty\" %}} {{% /button %}}

Neste capítulo, as suposições da **regressão linear** são testadas. O modelo `olsModel2` do capítulo anterior é o ponto de partida.

$stfdem_i = \beta_0 + \beta_1*stfeco_i + \beta_2*trstlgl_i + e_i$ (olsModel2)

Carregue o modelo de regressão no **Ambiente** ou recalcule o modelo mencionado acima.

Para `olsModel2`, obtemos a seguinte equação de regressão:

$$ stfdem_i = 0.67658 + 0.87361 * stfeco_i - 0.04212 * trstlgl_i + e_i $$

Os componentes da previsão são:

$$ \widehat{stfdem_i} = 0.67658 + 0.87361 * stfeco_i - 0.04212 * trstlgl_i $$

{{% tabs %}}
{{% tab name=\"Pergunta\" %}}
1. Qual é o efeito de `stfeco`?

2. Qual valor o modelo prevê para uma pessoa que avalia a satisfação com o desempenho econômico como $10$ e a confiança no sistema legal como $5$?

{{% /tab %}}
{{% tab name=\"Resolução\" %}}
1. O efeito de `stfeco` é de $0.87361$.

2. $\hat{stfdem} = 0.67658 + 0.87361 * 10 - 0.04212 * 5 = 9.20208$
{{% /tab %}}
{{% /tabs %}}

## Suposições da Regressão Linear

Como cientistas sociais, calculamos modelos que precisamos verificar em relação às suposições matemáticas. Existem várias funções com as quais podemos calcular a **diagnóstico de regressão**. Como raramente temos conjuntos de dados perfeitos nas ciências sociais (Não-Resposta, `NA's`), essas funções muitas vezes são muito restritivas. Na prática, muitas vezes decidimos sobre a aproximação das suposições, e não se as suposições são totalmente cumpridas. Frequentemente verificamos se possíveis violações são *suficientemente* pequenas para que a suposição seja válida.


**Estas são as suposições da regressão linear:**
{{% tabs %}}
{{% tab name=\"Suposições\" %}}
1. relação linear

2. $\epsilon_i \sim \mathcal{N}(0, \sigma^2)$

3. $Var(\epsilon_i) = \sigma^2$ (**Homoscedasticidade**)

4. $Cov(\epsilon_i, \epsilon_j) = 0, i \neq j$ (**Auto-Correlação**)

5. nenhuma dependência linear entre as variáveis independentes (**Multicolinearidade**)

6. nenhum caso influente
{{% /tab %}}
{{% tab name=\"Efeito em Caso de Violação\" %}}
1. estimadores enviesados

2. testes de significância inválidos, estimadores enviesados

3. estimadores enviesados

4. estimativa ineficiente

5. estimadores enviesados

6. estimadores enviesados
{{% /tab %}}
{{% tab name=\"Solução Possível\" %}}
1. transformação não linear

2. *nada!*

3. Transformação da variável dependente (ou da equação linear)

4. transformação não linear

5. remover variáveis

6. remover observações (mas deve ser teoricamente justificável!)
{{% /tab %}}
{{% tab name=\"Procedimento de Teste\" %}}
1. Inspeção de Gráficos

2. Inspeção de Gráficos (Teste de Shapiro-Wilk)

3. Teste de Breusch-Pagan

4. Estatística de Durbin-Watson

5. Correlação entre variáveis independentes e FIV / Fator de Tolerância

6. D de Cook
{{% /tab %}}
{{% /tabs %}}

Nas próximas páginas, você testará passo a passo as suposições.
