baseURL = "https://ilias.uni-giessen.de/data/JLUG/lm_data/lm_746772/"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
theme = "hugo-theme-learn"
themesdir = "./themes/"
metaDataFormat = "yaml"

[params]
  themeVariant = "jlug"
  description = "WBT Statistik<sup>+</sup>"
  author = "B. Philipp Kleer"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = ">"
  disableInlineCopyToClipBoard = true
  [assets]
    disableHLJS = true
[outputs]
home = [ "HTML", "RSS", "JSON"]

# Multilingual support
[Languages]
[Languages.de]
title = "Einstieg in R leicht gemacht"
weight = 1
languageCode = "de-DE"
languageName = "Deutsch"

[Languages.en]
title = "Make the start with R easy"
weight = 2
languageCode = "en-US"
languageName = "English"

[Languages.pt]
title = "Começar a utilizar o R de forma simples"
weight = 3
languageCode = "pt-BR"
languageName = "Português"

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Lernblock 1"
url = "../lb1/de/index.html"
weight = 10

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Lernblock 2"
url = "../lb2/de/index.html"
weight = 20

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Lernblock 3"
url = "../lb3/de/index.html"
weight = 30

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Lernblock 4"
url = "../lb4/de/index.html"
weight = 40

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Lernblock 5"
url = "../lb5/de/index.html"
weight = 40

[[Languages.de.menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Credits"
url = "./credits/index.html"
weight = 60

[[Languages.de.menu.shortcuts]]
name = "<i class='fab fa-gitlab'></i> Gitlab"
url = "https://gitlab.com/bpkleer/stats-with-r/"
weight = 70

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Study unit 1"
url = "../lb1/en/index.html"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Study unit 2"
url = "../lb2/en/index.html"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Study unit 3"
url = "../lb3/en/index.html"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Study unit 4"
url = "../lb4/en/index.html"
weight = 40

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Study unit 5"
url = "../lb5/en/index.html"
weight = 40

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Credits"
url = "../en/credits/index.html"
weight = 60

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-gitlab'></i> Gitlab"
url = "https://gitlab.com/bpkleer/stats-with-r/"
weight = 70

[[Languages.pt.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Unidade 1"
url = "../lb1/pt/index.html"
weight = 10

[[Languages.pt.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Unidade 2"
url = "../lb2/pt/index.html"
weight = 20

[[Languages.pt.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Unidade 3"
url = "../lb3/pt/index.html"
weight = 30

[[Languages.pt.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Unidade 4"
url = "../lb4/pt/index.html"
weight = 40

[[Languages.pt.menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> Unidade 5"
url = "../lb5/pt/index.html"
weight = 40

[[Languages.pt.menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> Créditos"
url = "../pt/credits/index.html"
weight = 60

[[Languages.pt.menu.shortcuts]]
name = "<i class='fab fa-gitlab'></i> Gitlab"
url = "https://gitlab.com/bpkleer/stats-with-r/"
weight = 70

[markup]
  [markup.highlight]
    codeFences = false
#    codeFences = true
#    hl_Lines = ""
#    lineNoStart = 1
#    lineNos = true
#    lineNumbersInTable = false
#   noClasses = true
#    style = "monokailight"
#    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

